site_name: Headless Comments Management System
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
nav:
- Introduction: index.md
- Creating your first comment: creating-your-first-comment.md
- Nested comments: nested-comments.md
- Registering users: registering-users.md
- Comment with an user: create-comment-with-user.md
