site_name: Comently
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
nav:
- Introduction: index.md
- Creating your first comment: creating-your-first-comment.md
- Nested comments: nested-comments.md
- Registering users: registering-users.md
- Comment with an user: create-comment-with-user.md
- List and retrieve comments: list-and-retrieve-comments.md
- Update a comment: update-a-comment.md
- Delete a comment: delete-a-comment.md
- Mentions in comments: mentions-in-comments.md
- Intended usage of the API: intended-usage-of-the-api.md
